# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cf1ced0224a25cbc61ccfaaefb5c50303b274e4c44a86887b7585182e9aa599fa74186e49ae93bf3370ba6991f33db7b19939499f26f35ce5da4725042acdea

test:
  secret_key_base: f3b815471b2c04280a7219819a6530a06005f48f0fe85fd23f218bbc18cd4859edc9b5b25440b8f1dcaba7d2b8e953fce821d745dcc17dc594b6ba9d4732255c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
